### ISSUE TITLE
Prettier Rule for Comment Line Length

### ISSUE THREAD

**Issue by atb-brown** [atb-brown/austin#38]
I would like some sort of prettier rule/plugin that will automatically split up long lines in comments to be multiple lines.

**Comment by avelynhc** [comment]
Hello, can I work on this? Thanks!

**Comment by atb-brown** [comment]
> @atb-brown Hello, can I work on this? Thanks!

Hello @avelynhc. Be my guest. :)

**Comment by avelynhc** [comment]
@atb-brown I don't think this would work. Based on my research, current version of Prettier does not support formatting the comments. Please refer to https://github.com/prettier/prettier/issues/265

**Comment by atb-brown** [comment]
@avelynhc Ahh, thank you for finding that and letting me know!

That is disappointing that it's not possible, but I appreciate having the closure. I had done a lot of Googling, but never came across this specific issue.

I'll go ahead and close this issue as unplanned.

**Comment by atb-brown** [comment]
I was able to accomplish this in #64 using the stylistic plugin for eslint.
