### ISSUE TITLE
Prettier Rule for React Component Property Sorting

### ISSUE THREAD

**Issue by atb-brown** [atb-brown/austin#39]
I would like a rule that will automatically sort all properties (and sub-properties) in my React component declarations.

For instance, this pattern
```jsx
<MyComp beta="bar" alpha={{z="foo1", y="foo2"}} />
```

Will be fixed to conform to this pattern
```jsx
<MyComp alpha={{y="foo2", z="foo1"}} beta="bar" />
```

**Comment by avelynhc** [comment]
@atb-brown I can work on this along with #38 as these are all related to Prettier. Let me know. Thanks!

**Comment by atb-brown** [comment]
Completed with #55 

Thanks, @avelynhc !!!
